services:
  frontend:
    image: node:20-alpine
    container_name: compia_frontend_dev
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      # Aponta para a API rodando no host (compia-bookstore-api)
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3333}
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"

volumes:
  node_modules:
